name: Build and push symfluence
on:
  push:
    branches:
      - symfluence
  pull_request:
    branches:
      - symfluence
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (example: v1.1.1)'
        required: true
        default: 'manual'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: cleanup disk space
      run: |
        sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
        df -h

    - name: Checkout files in repo
      uses: actions/checkout@main

    - name: Build and push the image to quay.io
      uses: jupyterhub/repo2docker-action@master
      with:
        # Make sure username & password/token pair matches your registry credentials
        DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        DOCKER_REGISTRY: "quay.io"
        IMAGE_NAME: "awiciroh/symfluence"
        ADDITIONAL_TAG: "v1.0.0"

    # Lets us monitor disks getting full as images get bigger over time
    - name: Show how much disk space is left
      run: df -h
